name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ls out
      # - name: Create release
      #   uses: softprops/action-gh-release@v0.1.5
      #   with:
      #     files: |
      #       *.dmg
      #       *.deb
      #       *.AppImage
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}