name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
